-- Postgres variant of db/migration/V1__init.sql — same schema, PG types.
-- Grove schema v1 — spec.md §6 (data model), minus passkey_credential
-- (Spring Security WebAuthn owns its tables) and push_subscription (lands with notifications).
-- Types follow the Java entities: bigint ids, date/timestamp/time for
-- LocalDate/LocalDateTime/LocalTime, text for enums, integer cents for money.

create table creche (
    id bigint generated by default as identity primary key,
    name text not null,
    address text,
    timezone text,
    logo_url text
);

create table app_user (
    id bigint generated by default as identity primary key,
    email text not null unique,
    name text not null,
    password_hash text,
    status text not null,
    created_at timestamp not null
);

create table membership (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_user (id),
    creche_id bigint not null references creche (id),
    role text not null
);

create table invite (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    email text not null,
    role text not null,
    token_hash text not null,
    expires_at timestamp not null,
    accepted_at timestamp
);

create table room (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    name text not null,
    capacity integer not null,
    age_min_months integer not null,
    age_max_months integer not null
);

create table child (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    first_name text not null,
    last_name text not null,
    dob date not null,
    room_id bigint references room (id),
    start_date date,
    end_date date,
    allergies text,
    medical_notes text,
    photo_consent boolean not null
);

create table guardian (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    user_id bigint references app_user (id),
    child_id bigint not null references child (id),
    relationship text,
    can_collect boolean not null,
    is_billing_contact boolean not null
);

create table emergency_contact (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    child_id bigint not null references child (id),
    name text not null,
    phone text,
    relationship text
);

create table attendance (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    child_id bigint not null references child (id),
    date date not null,
    check_in time,
    check_out time,
    status text not null,
    absence_reason text
);

create table diary_entry (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    child_id bigint not null references child (id),
    type text not null,
    body text,
    media_url text,
    recorded_by bigint references app_user (id),
    recorded_at timestamp not null,
    visible_to_parents boolean not null
);

create table fee_item (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    child_id bigint not null references child (id),
    name text not null,
    amount_cents integer not null,
    frequency text not null,
    valid_from date,
    valid_to date
);

create table subvention (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    child_id bigint not null references child (id),
    type text not null,
    hours_per_week double precision not null,
    hourly_rate_cents integer not null,
    reference_code text,
    valid_from date,
    valid_to date
);

create table invoice (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    family_key text not null,
    period_start date not null,
    period_end date not null,
    number text not null,
    status text not null,
    total_cents integer not null,
    due_date date,
    pdf_url text
);

create table invoice_line (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    invoice_id bigint not null references invoice (id),
    child_id bigint not null references child (id),
    description text,
    amount_cents integer not null
);

create table payment (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    invoice_id bigint not null references invoice (id),
    amount_cents integer not null,
    method text,
    paid_on date,
    reference text
);

create table conversation (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    type text not null,
    title text
);

create table conversation_member (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    conversation_id bigint not null references conversation (id),
    user_id bigint not null references app_user (id),
    last_read_at timestamp
);

create table message (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    conversation_id bigint not null references conversation (id),
    sender_id bigint references app_user (id),
    body text,
    attachment_url text,
    sent_at timestamp not null
);

create table form_template (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    title text not null,
    body_html text,
    requires_signature boolean not null
);

create table form_request (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    template_id bigint not null references form_template (id),
    child_id bigint not null references child (id),
    guardian_id bigint references guardian (id),
    status text not null,
    signed_at timestamp,
    signature_png_url text,
    signed_pdf_url text,
    signer_ip text
);

create table audit_log (
    id bigint generated by default as identity primary key,
    creche_id bigint not null references creche (id),
    user_id bigint references app_user (id),
    action text not null,
    entity text not null,
    entity_id bigint,
    at timestamp not null
);

create index idx_membership_creche on membership (creche_id);
create index idx_invite_creche on invite (creche_id);
create index idx_invite_email on invite (email);
create index idx_room_creche on room (creche_id);
create index idx_child_creche on child (creche_id);
create index idx_child_room on child (room_id);
create index idx_guardian_creche on guardian (creche_id);
create index idx_guardian_child on guardian (child_id);
create index idx_guardian_user on guardian (user_id);
create index idx_emergency_contact_creche on emergency_contact (creche_id);
create index idx_emergency_contact_child on emergency_contact (child_id);
create index idx_attendance_creche on attendance (creche_id);
create index idx_attendance_child_date on attendance (child_id, date);
create index idx_diary_entry_creche on diary_entry (creche_id);
create index idx_diary_entry_child on diary_entry (child_id);
create index idx_fee_item_creche on fee_item (creche_id);
create index idx_fee_item_child on fee_item (child_id);
create index idx_subvention_creche on subvention (creche_id);
create index idx_subvention_child on subvention (child_id);
create index idx_invoice_creche on invoice (creche_id);
create index idx_invoice_family_key on invoice (family_key);
create index idx_invoice_line_creche on invoice_line (creche_id);
create index idx_invoice_line_invoice on invoice_line (invoice_id);
create index idx_invoice_line_child on invoice_line (child_id);
create index idx_payment_creche on payment (creche_id);
create index idx_payment_invoice on payment (invoice_id);
create index idx_conversation_creche on conversation (creche_id);
create index idx_conversation_member_creche on conversation_member (creche_id);
create index idx_conversation_member_conversation on conversation_member (conversation_id);
create index idx_conversation_member_user on conversation_member (user_id);
create index idx_message_creche on message (creche_id);
create index idx_message_conversation on message (conversation_id);
create index idx_form_template_creche on form_template (creche_id);
create index idx_form_request_creche on form_request (creche_id);
create index idx_form_request_child on form_request (child_id);
create index idx_form_request_template on form_request (template_id);
create index idx_audit_log_creche on audit_log (creche_id);
create index idx_audit_log_user on audit_log (user_id);
